// SPDX-License-Identifier: GPL-3.0-or-later
pub mod activity;
pub mod albums;
pub mod artists;
pub mod download_clients;
pub mod events;
pub mod indexers;
pub mod metadata_profiles;
pub mod quality_profiles;
pub mod system;
pub mod tracks;
